# mrhandy: 1.2.1

- vars:
    - &remove_design_anchors [
        "#entry",
        "#exit",
        "entry",
        "exit",
        "gaf",
        "dotbelow",
        "dotabove",
        "twodotsbelow",
        "twodotsabove",
        "threedotsbelow",
        "threedotsabove",
        "hamzabelow",
        "hamzaabove",
      ]

# ----------------------------------------
# extract ufos from glyphs sources
- name: sources
  source: sources/Mehraban-Regular.glyphs
  tasks:
    - .glyphs.make_ufos

# ----------------------------------------
# compile static fonts:
#

- name: avestan fonts
  source: production/ufo/instances
  family: Mehraban Avestan
  tasks:
    - .ufo.cleanup:
      remove_anchors: *remove_design_anchors
    - .ufo.sync_names:
        strict: false
    - .ufo.add_features:
        feature_file: ["production/features/tables.avestan.fea", "production/features/features.fea"]

    - .ufo.make_otf
    - .ufo.make_ttf
    
    - .post.add_legacy_kern
    - .post.add_dsig

# ----------------------------------------
# compile webfonts
- name: web
  source: [fonts/MehrabanAvestan]
  family: [Mehraban Avestan Web]
  tasks:
    - .post.make_webfonts

